
CC=../../src/codegen.out

compile:
	$(CC) art-life.j--   > art-life.j--.s
	$(CC) art-select.j-- > art-select.j--.s
	$(CC) art-sieve.j--  > art-sieve.j--.s
	$(CC) gen.t1         > gen.t1.s
	$(CC) gen.t10        > gen.t10.s
	$(CC) gen.t11        > gen.t11.s
	$(CC) gen.t12        > gen.t12.s
	$(CC) gen.t13        > gen.t13.s
	$(CC) gen.t14        > gen.t14.s
	$(CC) gen.t15        > gen.t15.s
	$(CC) gen.t18        > gen.t18.s
	$(CC) gen.t22        > gen.t22.s
	$(CC) gen.t26        > gen.t26.s
	$(CC) gen.t29        > gen.t29.s
	$(CC) gen.t30        > gen.t30.s
	$(CC) gen.t31        > gen.t31.s
	$(CC) gen.t32        > gen.t32.s
	$(CC) gen.t33        > gen.t33.s
	$(CC) gen.t34        > gen.t34.s
	$(CC) gen.t38        > gen.t38.s
	$(CC) gen.t5         > gen.t5.s


runall: compile
	spim -f art-life.j--.s
	spim -f art-select.j--.s
	spim -f art-sieve.j--.s
	spim -f gen.t1.s
	spim -f gen.t10.s
	spim -f gen.t11.s
	spim -f gen.t12.s
	spim -f gen.t13.s
	spim -f gen.t14.s
	spim -f gen.t15.s
	spim -f gen.t18.s
	spim -f gen.t22.s
	spim -f gen.t26.s
	spim -f gen.t29.s
	spim -f gen.t30.s
	spim -f gen.t31.s
	spim -f gen.t32.s
	spim -f gen.t33.s
	spim -f gen.t34.s
	spim -f gen.t38.s
	spim -f gen.t5.s

